name: Build Package

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2.3.5

      - name: Build Sources
        run: |
          docker pull golang:latest
          docker pull alpine:latest
          docker build -t gochro:latest .
          docker tag gochro:latest docker.pkg.github.com/firefart/gochro/gochro:latest
          echo -n ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u firefart --password-stdin
          docker push docker.pkg.github.com/firefart/gochro/gochro:latest
